### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [goffalex/week3proj2#1]
It looks like this is version is quite a bit different from [what's hosted on Heroku](http://week3proj2.herokuapp.com/). Could you push a more up-to-date version to Heroku please?

**Comment by goffalex** [comment]
Oops I forgot to push it to Heroku. I've since done so and it should now fit the criteria for the showcase #2 of this week. However, when trying to add CSS to it for the showcase #3, it doesn't seem to be able to find my CSS files. I've tried some suggestions from stack overflow but nothings resolve it yet. Any suggestions?

**Comment by goffalex** [comment]
I should add that everything is working correctly when I view it locally on my machine. The issue comes in when I run rackup or push to Heroku.

**Comment by goffalex** [comment]
Got it figured out. Looks like the pathways weren't quite correct. Everything is updated in GitHub and Heroku now.

**Comment by chrisvfritz** [comment]
:+1: Excellent! Much better.
